package peluqueria;

import javax.swing.JOptionPane;

/**
 *
 * @author Julian Jimenez, Daniela Alexandra, Daniel Barrantes
 */
public class PeluqueriaTotal extends javax.swing.JFrame {

    /**
     * Creates new form PeluqueriaTotal
     */
    public PeluqueriaTotal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IniciarDia = new javax.swing.JButton();
        RegistrarAnita = new javax.swing.JButton();
        RegistrarRoberto = new javax.swing.JButton();
        RegistrarLucrecia = new javax.swing.JButton();
        RegistrarJosé = new javax.swing.JButton();
        VerTotales = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        A66 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        A4 = new javax.swing.JTextField();
        A5 = new javax.swing.JTextField();
        A1 = new javax.swing.JTextField();
        A11 = new javax.swing.JTextField();
        A22 = new javax.swing.JTextField();
        A33 = new javax.swing.JTextField();
        A44 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        C1 = new javax.swing.JTextField();
        C11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        C2 = new javax.swing.JTextField();
        C22 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        C3 = new javax.swing.JTextField();
        C33 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        C4 = new javax.swing.JTextField();
        C44 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        C5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        C66 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        B1 = new javax.swing.JTextField();
        B11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        B2 = new javax.swing.JTextField();
        B22 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        B3 = new javax.swing.JTextField();
        B33 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        B4 = new javax.swing.JTextField();
        B44 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        B5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        B66 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        D1 = new javax.swing.JTextField();
        D11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        D2 = new javax.swing.JTextField();
        D22 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        D3 = new javax.swing.JTextField();
        D33 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        D4 = new javax.swing.JTextField();
        D44 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        D5 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        D66 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarDia.setText("Iniciar Dia ");
        IniciarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarDiaActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 643, -1, -1));

        RegistrarAnita.setText("Registrar Anita ");
        RegistrarAnita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAnitaActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 643, -1, -1));

        RegistrarRoberto.setText("Registrar Roberto");
        RegistrarRoberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRobertoActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 643, -1, -1));

        RegistrarLucrecia.setText("Registrar Lucrecia");
        RegistrarLucrecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarLucreciaActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 643, -1, -1));

        RegistrarJosé.setText("Registrar José");
        RegistrarJosé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarJoséActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarJosé, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 643, -1, -1));

        VerTotales.setText("Ver Totales");
        VerTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(VerTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 643, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(948, 643, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Barberia UDEC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluqueria/Anita.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 123, 171));

        jLabel3.setText("Peinado :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, 20));

        jLabel8.setText("Tintura Cabello :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel9.setText("Total Recaudado : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel10.setText("Corte Dama :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 20));

        jLabel11.setText("Total Servicio :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel13.setText("Corte Caballero :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));

        A66.setText("$ 0. 00");
        A66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A66ActionPerformed(evt);
            }
        });
        jPanel1.add(A66, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 70, 30));

        A2.setText("0");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 30, 30));

        A3.setText("0");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 30, 30));

        A4.setText("0");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 30, 30));

        A5.setText("0");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, 30));

        A1.setText("0");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 30, 30));

        A11.setText("$ 0. 00");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });
        jPanel1.add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, 30));

        A22.setText("$ 0. 00");
        A22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A22ActionPerformed(evt);
            }
        });
        jPanel1.add(A22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 70, 30));

        A33.setText("$ 0. 00");
        A33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A33ActionPerformed(evt);
            }
        });
        jPanel1.add(A33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 30));

        A44.setText("$ 0. 00");
        A44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A44ActionPerformed(evt);
            }
        });
        jPanel1.add(A44, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 70, 30));

        jLabel33.setForeground(new java.awt.Color(0, 0, 153));
        jLabel33.setText("Ana");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 410, 246));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluqueria/Roberto.jpg"))); // NOI18N

        jLabel18.setText("Corte Caballero :");

        C1.setText("0");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        C11.setText("$ 0. 00");
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C11ActionPerformed(evt);
            }
        });

        jLabel19.setText("Corte Dama :");

        C2.setText("0");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C22.setText("$ 0. 00");
        C22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C22ActionPerformed(evt);
            }
        });

        jLabel20.setText("Tintura Cabello :");

        C3.setText("0");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        C33.setText("$ 0. 00");
        C33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C33ActionPerformed(evt);
            }
        });

        jLabel21.setText("Peinado :");

        C4.setText("0");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C44.setText("$ 0. 00");
        C44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C44ActionPerformed(evt);
            }
        });

        jLabel22.setText("Total Servicio :");

        C5.setText("0");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });

        jLabel23.setText("Total Recaudado : ");

        C66.setText("$ 0. 00");
        C66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C66ActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("Roberto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(C22, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(C11)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(C44, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(C33)))))
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C66, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(C33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(C3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C4)
                                    .addComponent(C44, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(C66, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluqueria/Jose.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 165));

        jLabel14.setText("Corte Caballero :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        B1.setText("0");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel3.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 30, 30));

        B11.setText("$ 0. 00");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        jPanel3.add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 30));

        jLabel12.setText("Corte Dama :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        B2.setText("0");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel3.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 30, 30));

        B22.setText("$ 0. 00");
        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });
        jPanel3.add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 80, 30));

        jLabel15.setText("Tintura Cabello :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        B3.setText("0");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel3.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 30, 30));

        B33.setText("$ 0. 00");
        B33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B33ActionPerformed(evt);
            }
        });
        jPanel3.add(B33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, 30));

        jLabel7.setText("Peinado :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        B4.setText("0");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel3.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 30, 30));

        B44.setText("$ 0. 00");
        B44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B44ActionPerformed(evt);
            }
        });
        jPanel3.add(B44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, 30));

        jLabel16.setText("Total Servicio :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        B5.setText("0");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel3.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 70, 30));

        jLabel17.setText("Total Recaudado : ");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        B66.setText("$ 0. 00");
        B66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B66ActionPerformed(evt);
            }
        });
        jPanel3.add(B66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, 30));

        jLabel30.setForeground(new java.awt.Color(0, 0, 153));
        jLabel30.setText("José");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 410, 246));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluqueria/Lucrecia.jpg"))); // NOI18N

        jLabel24.setText("Corte Caballero :");

        D1.setText("0");
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });

        D11.setText("$ 0. 00");
        D11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D11ActionPerformed(evt);
            }
        });

        jLabel25.setText("Corte Dama :");

        D2.setText("0");
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });

        D22.setText("$ 0. 00");
        D22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D22ActionPerformed(evt);
            }
        });

        jLabel26.setText("Tintura Cabello :");

        D3.setText("0");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });

        D33.setText("$ 0. 00");
        D33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D33ActionPerformed(evt);
            }
        });

        jLabel27.setText("Peinado :");

        D4.setText("0");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });

        D44.setText("$ 0. 00");
        D44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D44ActionPerformed(evt);
            }
        });

        jLabel28.setText("Total Servicio :");

        D5.setText("0");
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });

        jLabel29.setText("Total Recaudado : ");

        D66.setText("$ 0. 00");
        D66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D66ActionPerformed(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("Lucrecia");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(D66, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(D33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                            .addComponent(D22, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(D11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(D44)))
                                    .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel31)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(63, 63, 63)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(D33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(D5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(D66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 410, 280));

        jLabel34.setForeground(new java.awt.Color(0, 0, 153));
        jLabel34.setText("Sistema de control");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 647, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluqueria/fondo peluqueria.png"))); // NOI18N
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 1, 1060, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A66ActionPerformed
        try {
            int cantidadCorteCaballero = Integer.parseInt(A1.getText());
            int cantidadCorteDama = Integer.parseInt(A2.getText());
            int cantidadTintura = Integer.parseInt(A3.getText());
            int cantidadPeinado = Integer.parseInt(A4.getText());

            CorteCaballero corteCaballero = new CorteCaballero(cantidadCorteCaballero);
            CorteDama corteDama = new CorteDama(cantidadCorteDama);
            Tintura tintura = new Tintura(cantidadTintura);
            Peinado peinado = new Peinado(cantidadPeinado);

            double costoTotalCorteCaballero = corteCaballero.calcularCostoTotal();
            double costoTotalCorteDama = corteDama.calcularCostoTotal();
            double costoTotalTintura = tintura.calcularCostoTotal();
            double costoTotalPeinado = peinado.calcularCostoTotal();

            A11.setText("" + costoTotalCorteCaballero);
            A22.setText("" + costoTotalCorteDama);
            A33.setText("" + costoTotalTintura);
            A44.setText("" + costoTotalPeinado);

            double costoTotal = costoTotalCorteCaballero + costoTotalCorteDama + costoTotalTintura + costoTotalPeinado;

            A66.setText("" + costoTotal);

            int totalCantidadServicios = cantidadCorteCaballero + cantidadCorteDama + cantidadTintura + cantidadPeinado;

            A5.setText("" + totalCantidadServicios);
        } catch (NumberFormatException e) {
            A66.setText("Error: Ingrese números válidos");
        }


    }//GEN-LAST:event_A66ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        A5ActionPerformed(evt);
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        A5ActionPerformed(evt);
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        A5ActionPerformed(evt);
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed

    }//GEN-LAST:event_A5ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        A5ActionPerformed(evt);
    }//GEN-LAST:event_A1ActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A11ActionPerformed

    private void A22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A22ActionPerformed

    private void A33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A33ActionPerformed

    private void A44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A44ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B22ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B33ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B44ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B66ActionPerformed
        try {
            int cantidadCorteCaballero = Integer.parseInt(B1.getText());
            int cantidadCorteDama = Integer.parseInt(B2.getText());
            int cantidadTintura = Integer.parseInt(B3.getText());
            int cantidadPeinado = Integer.parseInt(B4.getText());

            double precioCorteCaballero = 8000;
            double precioCorteDama = 10500;
            double precioTintura = 40000;
            double precioPeinado = 15000;

            double costoTotalCorteCaballero = cantidadCorteCaballero * precioCorteCaballero;
            double costoTotalCorteDama = cantidadCorteDama * precioCorteDama;
            double costoTotalTintura = cantidadTintura * precioTintura;
            double costoTotalPeinado = cantidadPeinado * precioPeinado;

            B11.setText("" + costoTotalCorteCaballero);
            B22.setText("" + costoTotalCorteDama);
            B33.setText("" + costoTotalTintura);
            B44.setText("" + costoTotalPeinado);

            double costoTotal = costoTotalCorteCaballero + costoTotalCorteDama + costoTotalTintura + costoTotalPeinado;

            B66.setText("" + costoTotal);

            int totalCantidadServicios = cantidadCorteCaballero + cantidadCorteDama + cantidadTintura + cantidadPeinado;

            B5.setText("" + totalCantidadServicios);
        } catch (NumberFormatException e) {

            B66.setText("Error: Ingrese números válidos");
            B66.setText("Total a Pagar: ");
        }
    }//GEN-LAST:event_B66ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C11ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    private void C22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C22ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3ActionPerformed

    private void C33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C33ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4ActionPerformed

    private void C44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C44ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C5ActionPerformed

    private void C66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C66ActionPerformed
        try {
            int cantidadCorteCaballero = Integer.parseInt(C1.getText());
            int cantidadCorteDama = Integer.parseInt(C2.getText());
            int cantidadTintura = Integer.parseInt(C3.getText());
            int cantidadPeinado = Integer.parseInt(C4.getText());

            double precioCorteCaballero = 8000;
            double precioCorteDama = 10500;
            double precioTintura = 40000;
            double precioPeinado = 15000;

            double costoTotalCorteCaballero = cantidadCorteCaballero * precioCorteCaballero;
            double costoTotalCorteDama = cantidadCorteDama * precioCorteDama;
            double costoTotalTintura = cantidadTintura * precioTintura;
            double costoTotalPeinado = cantidadPeinado * precioPeinado;

            C11.setText("" + costoTotalCorteCaballero);
            C22.setText("" + costoTotalCorteDama);
            C33.setText("" + costoTotalTintura);
            C44.setText("" + costoTotalPeinado);

            double costoTotal = costoTotalCorteCaballero + costoTotalCorteDama + costoTotalTintura + costoTotalPeinado;

            C66.setText("" + costoTotal);

            int totalCantidadServicios = cantidadCorteCaballero + cantidadCorteDama + cantidadTintura + cantidadPeinado;

            C5.setText("" + totalCantidadServicios);
        } catch (NumberFormatException e) {

            C66.setText("Error: Ingrese números válidos");
            C66.setText("Total a Pagar: ");
        }
    }//GEN-LAST:event_C66ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void D11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D11ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ActionPerformed

    private void D22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D22ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void D33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D33ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void D44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D44ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D5ActionPerformed

    private void D66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D66ActionPerformed
        try {
            int cantidadCorteCaballero = Integer.parseInt(D1.getText());
            int cantidadCorteDama = Integer.parseInt(D2.getText());
            int cantidadTintura = Integer.parseInt(D3.getText());
            int cantidadPeinado = Integer.parseInt(D4.getText());

            double precioCorteCaballero = 8000;
            double precioCorteDama = 10500;
            double precioTintura = 40000;
            double precioPeinado = 15000;

            double costoTotalCorteCaballero = cantidadCorteCaballero * precioCorteCaballero;
            double costoTotalCorteDama = cantidadCorteDama * precioCorteDama;
            double costoTotalTintura = cantidadTintura * precioTintura;
            double costoTotalPeinado = cantidadPeinado * precioPeinado;

            D11.setText("" + costoTotalCorteCaballero);
            D22.setText("" + costoTotalCorteDama);
            D33.setText("" + costoTotalTintura);
            D44.setText("" + costoTotalPeinado);

            double costoTotal = costoTotalCorteCaballero + costoTotalCorteDama + costoTotalTintura + costoTotalPeinado;

            D66.setText("" + costoTotal);

            int totalCantidadServicios = cantidadCorteCaballero + cantidadCorteDama + cantidadTintura + cantidadPeinado;

            D5.setText("" + totalCantidadServicios);
        } catch (NumberFormatException e) {

            D66.setText("Error: Ingrese números válidos");
            D66.setText("Total a Pagar: ");
        }
    }//GEN-LAST:event_D66ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void IniciarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarDiaActionPerformed
        //registro de Anita
        A1.setText("" + 0);
        A2.setText("" + 0);
        A3.setText("" + 0);
        A4.setText("" + 0);
        A5.setText("" + 0);
        A66.setText("" + 0);
        A11.setText("" + 0);
        A22.setText("" + 0);
        A33.setText("" + 0);
        A44.setText("" + 0);
        //resgistro de jose
        B1.setText("" + 0);
        B2.setText("" + 0);
        B3.setText("" + 0);
        B4.setText("" + 0);
        B5.setText("" + 0);
        B66.setText("" + 0);
        B11.setText("" + 0);
        B22.setText("" + 0);
        B33.setText("" + 0);
        B44.setText("" + 0);
        //registro de roberto
        C1.setText("" + 0);
        C2.setText("" + 0);
        C3.setText("" + 0);
        C4.setText("" + 0);
        C5.setText("" + 0);
        C66.setText("" + 0);
        C11.setText("" + 0);
        C22.setText("" + 0);
        C33.setText("" + 0);
        C44.setText("" + 0);
        //registro de lucrecia
        D1.setText("" + 0);
        D2.setText("" + 0);
        D3.setText("" + 0);
        D4.setText("" + 0);
        D5.setText("" + 0);
        D66.setText("" + 0);
        D11.setText("" + 0);
        D22.setText("" + 0);
        D33.setText("" + 0);
        D44.setText("" + 0);
    }//GEN-LAST:event_IniciarDiaActionPerformed

    private void RegistrarAnitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAnitaActionPerformed
        String datoA1 = A1.getText();
        String datoA2 = A2.getText();
        String datoA3 = A3.getText();
        String datoA4 = A4.getText();

        String mensaje = "Datos de Los Servicios de Anita:\n"
                + "A1: " + datoA1 + "\n"
                + "A2: " + datoA2 + "\n"
                + "A3: " + datoA3 + "\n"
                + "A4: " + datoA4 + "\n";

        JOptionPane.showMessageDialog(this, mensaje, "Datos de JLabel A", JOptionPane.INFORMATION_MESSAGE);
        A66ActionPerformed(evt);

    }//GEN-LAST:event_RegistrarAnitaActionPerformed

    private void RegistrarRobertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRobertoActionPerformed
        String datoC1 = C1.getText();
        String datoC2 = C2.getText();
        String datoC3 = C3.getText();
        String datoC4 = C4.getText();

        String mensaje = "Datos de Los Servicios de Roberto:\n"
                + "C1: " + datoC1 + "\n"
                + "C2: " + datoC2 + "\n"
                + "C3: " + datoC3 + "\n"
                + "C4: " + datoC4 + "\n";

        JOptionPane.showMessageDialog(this, mensaje, "Datos de JLabel B", JOptionPane.INFORMATION_MESSAGE);
        C66ActionPerformed(evt);

    }//GEN-LAST:event_RegistrarRobertoActionPerformed

    private void RegistrarLucreciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarLucreciaActionPerformed
        String datoD1 = D1.getText();
        String datoD2 = D2.getText();
        String datoD3 = D3.getText();
        String datoD4 = D4.getText();

        String mensaje = "Datos de Los Servicios de Lucrecia:\n"
                + "D1: " + datoD1 + "\n"
                + "D2: " + datoD2 + "\n"
                + "D3: " + datoD3 + "\n"
                + "D4: " + datoD4 + "\n";

        JOptionPane.showMessageDialog(this, mensaje, "Datos de JLabel C", JOptionPane.INFORMATION_MESSAGE);
        D66ActionPerformed(evt);
    }//GEN-LAST:event_RegistrarLucreciaActionPerformed

    private void RegistrarJoséActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarJoséActionPerformed
        String datoB1 = B1.getText();
        String datoB2 = B2.getText();
        String datoB3 = B3.getText();
        String datoB4 = B4.getText();

        String mensaje = "Datos de Los Servicios de José:\n"
                + "B1: " + datoB1 + "\n"
                + "B2: " + datoB2 + "\n"
                + "B3: " + datoB3 + "\n"
                + "B4: " + datoB4 + "\n";

        JOptionPane.showMessageDialog(this, mensaje, "Datos de JLabel D", JOptionPane.INFORMATION_MESSAGE);
        B66ActionPerformed(evt);
    }//GEN-LAST:event_RegistrarJoséActionPerformed

    private void VerTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTotalesActionPerformed
        try {
            double valorA1 = Double.parseDouble(A66.getText());
            double valorB1 = Double.parseDouble(B66.getText());
            double valorC1 = Double.parseDouble(C66.getText());
            double valorD1 = Double.parseDouble(D66.getText());
            
            ServicioCorte servicioA = new ServicioCorte(1, valorA1); 
            ServicioCorte servicioB = new ServicioCorte(1, valorB1);
            ServicioCorte servicioC = new ServicioCorte(1, valorC1);
            ServicioCorte servicioD = new ServicioCorte(1, valorD1);
            
            double costoTotalA = servicioA.calcularCostoTotal();
            double costoTotalB = servicioB.calcularCostoTotal();
            double costoTotalC = servicioC.calcularCostoTotal();
            double costoTotalD = servicioD.calcularCostoTotal();
            
            double suma = costoTotalA + costoTotalB + costoTotalC + costoTotalD;

            String mensaje = "El total es: " + suma;

            JOptionPane.showMessageDialog(null, mensaje, "El total por todos los peluqueros es :", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Alguno de los valores en los JLabel no es un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        try {
            int valorZ1 = Integer.parseInt(A5.getText());
            int valorZ2 = Integer.parseInt(B5.getText());
            int valorZ3 = Integer.parseInt(C5.getText());
            int valorZ4 = Integer.parseInt(D5.getText());

            int suma = valorZ1 + valorZ2 + valorZ3 + valorZ4;

            String mensaje = "El total de servicios fue de :" + suma;

            JOptionPane.showMessageDialog(null, mensaje, "El total de Servicios", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Alguno no es valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        

    }//GEN-LAST:event_VerTotalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeluqueriaTotal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A11;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A22;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField A33;
    private javax.swing.JTextField A4;
    private javax.swing.JTextField A44;
    private javax.swing.JTextField A5;
    private javax.swing.JTextField A66;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B11;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField B22;
    private javax.swing.JTextField B3;
    private javax.swing.JTextField B33;
    private javax.swing.JTextField B4;
    private javax.swing.JTextField B44;
    private javax.swing.JTextField B5;
    private javax.swing.JTextField B66;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C11;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField C22;
    private javax.swing.JTextField C3;
    private javax.swing.JTextField C33;
    private javax.swing.JTextField C4;
    private javax.swing.JTextField C44;
    private javax.swing.JTextField C5;
    private javax.swing.JTextField C66;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D11;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D22;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField D33;
    private javax.swing.JTextField D4;
    private javax.swing.JTextField D44;
    private javax.swing.JTextField D5;
    private javax.swing.JTextField D66;
    private javax.swing.JButton IniciarDia;
    private javax.swing.JButton RegistrarAnita;
    private javax.swing.JButton RegistrarJosé;
    private javax.swing.JButton RegistrarLucrecia;
    private javax.swing.JButton RegistrarRoberto;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerTotales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
